# Generated by Django 4.1.2 on 2023-01-02 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shows", "0006_add_rate_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="show",
            name="payment_method",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Cash"),
                    (1, "Venmo"),
                    (2, "PayPal"),
                    (3, "Check"),
                ],
                default=0,
            ),
        ),
    ]
